<section class="h-screen w-screen flex items-center justify-center absolute">
  <div class="flex flex-col p-14 border-solid border-2 border-black bg-white">
    <h4 class="text-3xl uppercase text-center m-8">Choisissez vôtre taille</h4>
    <p class="text-l uppercase text-center m-6">
      Taille disponibles pour votre couleurs :
    </p>
    <div
      class="flex flex-row gap-8 items-center justify-center w-full m-1 flex-wrap mb-8 mt-4"
      id="tailles"
    ></div>
  </div>
</section>
