<div
  class="w-min flex flex-row items-center justify-center border-solid border-2 border-black"
>
  <div class="p-2 hover:cursor-pointer">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="14"
      height="14"
      viewBox="0 0 14 14"
      fill="none"
    >
      <path
        d="M14 7.99805H8V13.998H6V7.99805H0V5.99805H6V-0.00195312H8V5.99805H14V7.99805Z"
        fill="black"
      />
    </svg>
  </div>
  <p class="p-2">{{nombre}}</p>
  <div class="p-2 hover:cursor-pointer">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="14"
      height="2"
      viewBox="0 0 14 2"
      fill="none"
    >
      <path d="M14 1.99805H0V-0.00195312H14V1.99805Z" fill="black" />
    </svg>
  </div>
</div>
