<div
  class="flex flex-col items-center justify-center border-solid border-2 border-black w-10/12 mt-10"
>
  <div class="flex flex-row w-full">
    <p
      class="w-full text-center border-solid border-2 border-black text-l uppercase p-2"
    >
      panier
    </p>
    <p
      class="text-l uppercase p-2 border-solid border-2 border-black hover:cursor-pointer"
    >
      favoris
    </p>
  </div>
  <h4
    class="text-l uppercase w-full text-left p-2 border-solid border-2 border-black hover:cursor-pointer"
  >
    Vous souhaitez une commande cadeau ?
  </h4>
  <div
    class="flex flex-col items-center justify-center border-solid border-2 border-black w-full"
  >
    <p class="text-l text-left w-full p-4 uppercase">articles</p>
    <div class="flex flex-col">
      <div class="flex flex-col w-full p-4" id="products-panier"></div>
    </div>
  </div>
</div>
