<div
  class="flex flex-col items-center justify-center border-solid border-2 border-black w-10/12 mt-10"
>
  <div class="flex flex-row w-full">
    <p
      class="w-full text-center border-solid border-2 border-black text-l uppercase p-2 lg:text-2xl lg:p-4"
    >
      panier
    </p>
    <p
      class="text-l uppercase p-2 border-solid border-2 border-black hover:cursor-pointer lg:text-2xl lg:p-4"
    >
      favoris
    </p>
  </div>
  <h4
    class="text-l uppercase w-full text-left p-2 border-solid border-2 border-black hover:cursor-pointer lg:text-xl lg:p-4"
  >
    Vous souhaitez une commande cadeau ?
  </h4>
  <div
    class="flex flex-col items-center justify-center border-solid border-2 border-black w-full"
  >
    <p class="text-l text-left w-full p-4 uppercase lg:text-xl lg:p-8">
      articles
    </p>
    <div class="flex flex-col">
      <div class="flex flex-col w-full p-4 gap-8" id="products-panier"></div>
    </div>
  </div>
  <p
    class="text-center text-white bg-black hover:text-black hover:bg-white w-full text-l uppercase p-2 border-solid border-2 border-black hover:cursor-pointer lg:text-2xl lg:p-4 hover:ease-in-out"
  >
    Commander
  </p>
</div>
